service: desafio-bgc

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    PRODUCTS_TABLE: ProdutosBestsellers
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - !GetAtt ProdutosTable.Arn
            - !Join ["/", [!GetAtt ProdutosTable.Arn, "index", "CategoryIndex"]]

plugins:
  - serverless-esbuild

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.git/**"
    - "!.serverless/**"
    - "!.build/**"

resources:
  Resources:
    ProdutosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProdutosBestsellers
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: category
            AttributeType: S
          - AttributeName: ranking
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CategoryIndex
            KeySchema:
              - AttributeName: category
                KeyType: HASH
              - AttributeName: ranking
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

functions:
  getTop3BestSellers:
    handler: src/functions/get-top-3.getTop3BestSellersByCategory
    description: fetch top 3 best sellers by category
    runtime: nodejs20.x
    memorySize: 128
    timeout: 3
    events:
      - http:
          path: /bestsellers/top3
          method: get
          cors: true

  getAllBestSellers:
    handler: src/functions/get-all-by-category.getAllBestSellersByCategory
    description: fetch all best sellers by category
    runtime: nodejs20.x
    memorySize: 128
    timeout: 3
    events:
      - http:
          path: /bestsellers/{category}
          method: get
          cors: true

  getDocs:
    handler: src/functions/get-docs.getDocs
    description: fetch app documentation
    runtime: nodejs20.x
    memorySize: 128
    timeout: 3
    events:
      - http:
          path: /docs
          method: get
          cors: true
